multiagent_techtree_1_shears_with_2_iron_ingot:
  goal: techtree 1 shears
  agent_names:
  - andy
  - randy
  agent_number: 2
  initial_inventory:
    andy:
      iron_ingot: 1
    randy:
      iron_ingot: 1
  target: shears
  number_of_target: 1
  type: techtree
  personalities:
    Alice: Conscientiousness
    Bob: Agreeableness
  script: there are some misunderstandings between Bob and Alice, Bob says Alice was wrong, but Alice says Bob was wrong, then Bob apologized for his wrong.
  system_instructions: []
  blocked_actions: 
    andy:
      - "!collectBlocks"
      - "!collectAllBlocks"
    randy:
      - "!collectBlocks"
      - "!collectAllBlocks"n